[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#1a1a1a"
foreground = "#e6e6e6"

[env]
TERM = "alacritty"

[font]
builtin_box_drawing = true
size = 12.0

[font.normal]
family = "SauceCodePro Nerd Font"

