font_family JetBrainsMono Nerd Font
font_size 12
disable_ligatures always
cursor_blink_interval -1 ease-in-out
cursor_trail 1
cursor_shape beam
scrollbar never
mouse_hide_wait 0
paste_actions no-op
enable_audio_bell no
remember_window_size no
initial_window_width 100c
initial_window_height 25c
window_resize_step_cells 1
window_resize_step_lines 1
window_border_width 2
window_margin_width 4
window_padding_width 4
tab_bar_style powerline
tab_powerline_style slanted
background_opacity 0.8
background_blur 1
shell_integration no-cursor
confirm_os_window_close 0
map ctrl+shift+plus change_font_size all +1
map ctrl+shift+minus change_font_size all -2
map ctrl+shift+0 change_font_size all 0

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
