layerrule = animation popin, rofi
layerrule = animation fade, hyprpicker
layerrule = animation slide left, swaync-control-center
layerrule = animation slide top, swaync-notification-window
layerrule = animation fade, swww-daemon
