theme = "catppuccin-mocha-blue"
editor = ""
dir_editor = ""
auto_check_update = true
cd_on_quit = true
default_open_file_preview = true
show_image_preview = true
show_panel_footer_info = true
default_directory = "."
file_size_use_si = false
default_sort_type = 0
sort_order_reversed = false
case_sensitive_sort = false
shell_close_on_success = false
debug = false
code_previewer = ""
nerdfont = true
transparent_background = true
file_preview_width = 0
sidebar_width = 20
border_top = '─'
border_bottom = '─'
border_left = '│'
border_right = '│'
border_top_left = '╭'
border_top_right = '╮'
border_bottom_left = '╰'
border_bottom_right = '╯'
border_middle_left = '├'
border_middle_right = '┤'
metadata = true
enable_md5_checksum = false
